name: Check for updates

on:
    push:
    schedule:
      - cron: "0 0 * * 5" # every friday at 00:00 UTC

jobs:
    checkForUpdates:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: Run generate_code.sh
          run: ./scripts/generate_code.sh

        - name: Check for unstaged changes
          run: |
                if [[ `git status --porcelain` ]]; then
                    echo "This repository needs to be updated. Please run ./scripts/generate_code.sh and commit the changes."
                    git diff
                    exit 1
                fi

        - name: Check for outdated dependencies
          run: |
                cargo install cargo-outdated
                cargo outdated --exit-code 1
